### ISSUE TITLE
Wasm instructions

### ISSUE THREAD

**Issue by jsyrjala** [MasterQ32/zero-graphics#2]
Instructions for wasm do not seem to work.

```
zig build install run-wasm
Now visit http://127.0.0.1:8000/index.htm to see the demo.
```

This creates a web server that serves files from top-level `www` directory, but the build process puts files to `zig-out/www` directory. Also the file the html file in `zig-out/www` is `demo_application.htm`, not `index.html`.

**Comment by ikskuh** [comment]
Oh, thanks! This needs to be changed, as i improved the build process a lot in regards of Wasm
